views.go
decrease logging level for content length limit exceeded for appendGlobalLog errors
=> EVG-12770: warn instead of error on 413

.gitignore, views.go
I went with the low-effort approach of allowing all origins because we don't have any authentication system, so trying to control origins is kind of a moot point
=> EVG-14250 allow all origins on GETs

background.go, db/db.go, env/environment.go, env/stats_cache.go, env/stats_cache_test.go, go.mod, logkeeper_test.go, main/logkeeper.go, schema.go, schema_test.go, views.go, views_test.go
[EVG-17145](https://jira.mongodb.org/browse/EVG-17145)
This is intended to be mostly the same as #66 except that it's not based on the now reverted mgo -> mongo commit (#62). Because we believe the revert is likely permanent this had to be done over from scratch.
=> EVG-17145 stats cache take 3

logger.go, logger_test.go
[EVG-17147](https://jira.mongodb.org/browse/EVG-17147)
I forgot about the race detector when I wrote the tests. They were not coordinating around accesses to the mock sender's message slice because the test would spin on checking the slice while the logger loop wrote to it from another goroutine. 
I rewrote the tests that were racing so the loop and test are all the same goroutine. The tests were taking a while so I made the ticker interval configurable in order to speed up the tests.
=> EVG-17147 fix race in test

logger.go, logger_test.go
[EVG-17147](https://jira.mongodb.org/browse/EVG-17147)
The panics from the previous deploy were due to failing [this check](https://github.com/gonum/gonum/blob/1180659542815ddb51545f83860386272ebf0d9b/stat/stat.go#L504-L506). Looking over the entire list of checks there it looks like we're safe now.
=> EVG-17147 sort slice

logger.go
[EVG-17451](https://jira.mongodb.org/browse/EVG-17451)
Separate the routes based on the HTTP method. 
I tried it out with the smoke test. I got two separate messages in `logkeeperapp.log` for the `/build/{build_id}/test/{test_id}` route
```
route='[GET] /build/{build_id}/test/{test_id}'
```
and 
```
route='[POST] /build/{build_id}/test/{test_id}'
```
=> EVG-17451 differentiate HTTP methods

logger.go, logger_test.go
[EVG-17451](https://jira.mongodb.org/browse/EVG-17451)
One more improvement to logging: it's not helpful to log messages for routes that haven't seen any requests. For one thing, it's unnecessarily consuming our Splunk allowance. Also, it's an extra step to filter them out when we're trying to find averages.
=> EVG-17451 skip empty messages

main/logkeeper.go, makefile, storage/storage.go
[EVG-17461](https://jira.mongodb.org/browse/EVG-17461)
This will make logkeeper start so we can continue to deploy until we get the expected environment variables in place ([EVG-17460](https://jira.mongodb.org/browse/EVG-17460)).
=> EVG-17461 log to file

storage/storage.go, storage/storage_test.go
[EVG-17460](https://jira.mongodb.org/browse/EVG-17460)
Since we'll be using an IAM role for access we no longer need static credentials.
=> EVG-17460 env variables

logger.go
[EVG-17463](https://jira.mongodb.org/browse/EVG-17463)
Use 1024^2 for `bytesPerMB` instead of 1000000.
=> EVG-17463 use the correct unit

model/build.go, storage/persistence.go, storage/persistence_test.go, storage/storage_model.go, views.go
[EVG-17150](https://jira.mongodb.org/browse/EVG-17150)
Write test metadata to S3. Mostly the same as creating a build.
I added a field to the build document in the db that will indicate if we're duplicating to S3. If we are then all subsequent operations go to S3 too. This strategy is just for testing. In the goal state we'll stop doing this and just write everything to S3 (instead of the db).
=> EVG-17150 upload test metadata

model/log.go, model/log_test.go
[EVG-17467](https://jira.mongodb.org/browse/EVG-17467)
Since https://github.com/evergreen-ci/logkeeper/commit/cb88682ab734bf7b06f86d67dae87c230df17b92 a LogLine was getting marshalled to/from BSON as an object. This isn't compatible with existing logs.
Implement the [Getter](https://pkg.go.dev/gopkg.in/mgo.v2@v2.0.0-20190816093944-a6b53ec6cb22/bson#Getter) and [Setter](https://pkg.go.dev/gopkg.in/mgo.v2@v2.0.0-20190816093944-a6b53ec6cb22/bson#Setter) interfaces so the driver will marshal/unmarshal in the original format. Test `GetBSON` by verifying that LogLine is marshalled into the db is as expected and test `SetBSON` by verifying that a LogLine is unmarshalled from the db.
=> EVG-17467 marshal/unmarshal LogLine

storage/persistence_test.go, storage/retrieval_test.go, storage/storage_model.go, storage/storage_model_test.go, testdata/between/builds/5a75f537726934e4b62833ab6d5dca41/tests/62dba0159041307f697e6ccc/metadata.json, testdata/between/builds/5a75f537726934e4b62833ab6d5dca41/tests/72dba0159041307f697e6ccd/metadata.json, testdata/overlapping/builds/5a75f537726934e4b62833ab6d5dca41/tests/62dba0159041307f697e6ccc/metadata.json, testdata/simple/builds/5a75f537726934e4b62833ab6d5dca41/tests/62dba0159041307f697e6ccc/metadata.json
We should keep storing metadata and phase since clients are passing
it and may want it back, even though we don't currently use it
in the code base. We would like to minimize data model changes
for our project.
=> EVG-17492: Continue to store command and phase in metadata.json

model/build.go, model/build_test.go, views.go
This will allow us to constant time lookup builds based on
builder and buildNum without having to add an additional S3
hierarchy.
=> EVG-17493: Generate build keys from builder and buildNum.

storage/retrieval.go, storage/retrieval_test.go, storage/storage_model.go, views.go
This follows the same pattern of "provide the 's3' query parameter to get the build from S3, which we will use for testing once all the data has been replicated to both places.
=> EVG-17154: Add ability to retrieve build from S3

main/logkeeper.go, makefile
[EVG-17461](https://jira.mongodb.org/browse/EVG-17461)
Revert the change we made in https://github.com/evergreen-ci/logkeeper/pull/88 and go back to using the S3 bucket. 
This is dependent on the changes to the fabfile to create an environment file and the changes to the chef configuration to use the environment file. Don't merge this until those are in place.
=> EVG-17461 use S3 bucket again

.evg.yml, featureswitch/featureswitch.go, featureswitch/featureswitch_test.go, makefile, views.go
This will allow us to set a percentage of builds being written to
S3. I opted to make this a hash of the build ID rather than random
for a few reasons:
1. When we use this for ramping up fetching from S3, it will ensure
that users won't alternate between code paths for fetching the same
build. This should avoid weird bugs for clients and aid in
debugging.
2. It will make debugging in general less based on chance. If you
put the same build name and id to the same configuration, you'll
hit the same code path.
=> EVG-17160: Add featureswitch code for writing builds.

main/logkeeper.go
[EVG-17461](https://jira.mongodb.org/browse/EVG-17461)
I made a wrong assumption about [flag.String](https://github.com/evergreen-ci/logkeeper/blob/b108605d58a90c8c17d7d641b45419f5e5736a45/main/logkeeper.go#L38): the returned string pointer is never nil. If the flag isn't specified the return is always set to whatever the default value is, in this case the empty string.
=> EVG-17461 check for empty string

storage/storage_model.go, storage/storage_model_test.go
This plays better with all the S3 APIs, since AWS likes to
strip double slashes, including those in REST requests that
correspond to the beginning of a key value.
=> EVG-17426: Switch to not prefixing our keys with '/'

go.mod, go.sum, views.go
This adds gzip to the major log returning routes, which should
substantially reduce their size.
=> EVG-17410: Add gzipping to logkeeper routes.

views.go
[EVG-17651](https://jira.mongodb.org/browse/EVG-17651)
Since [89dc3a](https://github.com/evergreen-ci/logkeeper/commit/89dc3a21325997758eea9064b3a25cd26e1e1d32) we've been unable to load S3 logs. We think the issue is that the child context is getting cancelled before the logs are loaded. This PR delegates cancelling the child context to the caller.
=> EVG-17651 close context

storage/persistence.go, storage/persistence_test.go, storage/retrieval.go, storage/retrieval_test.go, storage/storage_test.go, views.go
JIRA: https://jira.mongodb.org/browse/EVG-17602, https://jira.mongodb.org/browse/EVG-17621
I made the writes to S3 as independent as possible but we still rely on the `s3` field from the build model when uploading logs and test metadata. This isn't a big deal, though, because when we are ready to remove the DB code we can just ignore it since all writes will go to S3.
I tested that this works in staging.
=> EVG-17602, EVG-17621: Parallelize and independently write to S3

main/logkeeper.go
[EVG-17980](https://jira.mongodb.org/browse/EVG-17980)
If we remove the option before we remove it from the systemd unit file then the application will not start. If we remove it from the unit file before we deploy the application then the application won't start (like if it exits and systemd restarts it).
This PR adds the option back (and ignores it) so we can update the unit file at our leisure.
=> EVG-17980 add temporary dbhost flag

views.go
This adds a query param that will return an object with a task and build id for a given build or build/test combo.
=> EVG-18043 Add param to expose task metadata

.gitignore, model/build.go, model/build_test.go, model/test.go, model/test_test.go, smoke/smoke_test.go, testdata/between/builds/5a75f537726934e4b62833ab6d5dca41/tests/0de0b6b3bf4ac6400000000000000000/metadata.json, testdata/between/builds/5a75f537726934e4b62833ab6d5dca41/tests/0de0b6b3cb3688400000000000000000/metadata.json, testdata/delayed/builds/5a75f537726934e4b62833ab6d5dca41/tests/0de0b6b3bf3b84000000000000000000/metadata.json, testdata/nolines/builds/5a75f537726934e4b62833ab6d5dca41/tests/de0b6b3a764000000000000/metadata.json, testdata/overlapping/builds/5a75f537726934e4b62833ab6d5dca41/tests/0de0b6b3bf3b84000000000000000000/metadata.json, testdata/precision/builds/5a75f537726934e4b62833ab6d5dca41/tests/17046404de28123f0000000000000000/metadata.json, testdata/simple/builds/5a75f537726934e4b62833ab6d5dca41/tests/17046404de18d0000000000000000000/metadata.json, views.go, views_test.go
This patch allows for the inclusion of a `task_execution` parameter to be sent to logkeeper as metadata. It is an int.
=> EVG-18048: Update logkeeper to accept "Execution" as build/test metadata

logger.go, logger_test.go
JIRA: https://jira.mongodb.org/browse/EVG-17910
This avoids setting the std dev to NaN, which cannot be marshalled to JSON in the Splunk sender.
=> EVG-17910: Set response logger std dev to 0 when sample size is 1

views.go, views_test.go
JIRA: https://jira.mongodb.org/browse/EVG-18291
- Add a `metadata` parameter to the existing `/build/{build_id}` route that returns the build and test metadata as JSON.
- Return the test metadata instead of the build metadata for the `build/{build_id}/test/{test_id}` route.
- Add tests for all of the metadata routes.
=> EVG-18291: Create a view build metadata route

model/build.go, model/build_test.go
[EVG-18316](https://jira.mongodb.org/browse/EVG-18316)
List operations are 10x more expensive than Get operations (per [the docs](https://aws.amazon.com/s3/pricing/)).
In the short term let's switch the List to a Get. Afterwards it probably makes sense to add a [HeadObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) to pail.
=> EVG-18316 switch List to Get

model/log.go, model/log_test.go, requests.go, views.go
[EVG-18629](https://jira.mongodb.org/browse/EVG-18629)
It appears that unmarshaling by using the decoder directly (as in [this example](https://pkg.go.dev/encoding/json#example-Decoder.Decode-Stream)) uses about half the time and an order of magnitude less memory/fewer allocations.
From inspection of the CPU profiles, (with sufficient handwaving) it could be the reason is that when we were calling the regular json.Unmarshal that called into the custom unmarshaler we were having it do double the work: the custom marshaler called back out to the json library to parse a new byte array for the inner array. At the same time the original call to the json library also needed to parse the inner array to keep track of where we were up to.
The before and after is striking:
before
```
go test …
```
=> EVG-18629 unmarshal log lines directly
